### ISSUE TITLE
image cytomine/software_router not found.

### ISSUE THREAD

**Issue by soltiger** [cytomine/Cytomine-bootstrap#1]
I'm using Cytomine-bootstrap v1.0. and I'm failing to install Cytomine with it.

When following installation instructions ([http://doc.cytomine.be/pages/viewpage.action?pageId=10715266]) and getting to the step where I run 
`sudo sh ./start_deploy.sh`
I'm getting error:

> docker: Error: image cytomine/software_router not found.

I then tried to build software_router manually, by entering
`sudo docker build -t="cytomine/software_router" .`
in software_router directory and got the following error:

> # 
> ## ERROR: Failure: RuntimeError (lena() is no longer included in SciPy, please use ascent() or face() instead)
> 
> ...
>   File "/root/anaconda/lib/python2.7/site-packages/scipy/misc/common.py", line 376, in lena
>     raise RuntimeError('lena() is no longer included in SciPy, please use '
> RuntimeError: lena() is no longer included in SciPy, please use ascent() or face() instead
> Ran 6348 tests in 169.183s
> FAILED (SKIP=17, errors=1)
> make: **\* [test-code] Error 1

**Comment by geektortoise** [comment]
The new scipy version in conda (0.17.0) is not backward compatible.
The fonction lena has been deleted.

To fix it, add the following line 
RUN conda install scipy=0.16.1 --yes
below
RUN conda install opencv --yes
into the software-router/Dockerfile

**Comment by jacmarjorie** [comment]
I also had this issue, thanks for the fix. There were a couple of additional things I needed to add in order for this image to build successfully on CentOS Linux release 7.2.1511 (Core).

**FIRST**: Similar to the issue I listed [here](https://github.com/cytomine/Cytomine-core/issues/1073), add to Dockerfile `ENV DEBIAN_FRONTEND noninteractive`. That avoids this error:

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
```

**SECOND**: The groovy installation was failing at sdkman due to not retrieving the ca certificates, this was fixed by adding this like to the Dockerfile, as well: `ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt`. For reference, here is the error:

```
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
Extract script archive...
[/root/.sdkman/tmp/res-4.0.32.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /root/.sdkman/tmp/res-4.0.32.zip or
        /root/.sdkman/tmp/res-4.0.32.zip.zip, and cannot find /root/.sdkman/tmp/res-4.0.32.zip.ZIP, period.
Install scripts...
mv: cannot stat ‘/root/.sdkman/tmp/stage/sdkman-init.sh’: No such file or directory
mv: cannot stat ‘/root/.sdkman/tmp/stage/sdkman-*’: No such file or directory
```

Again, might be worth looking into.

**Comment by geektortoise** [comment]
A cytomine/software_router image is now on DockerHub.
As now, you don't have to build the images,  you will won't have this problem during the installation.
