### ISSUE TITLE
software_router issues

### ISSUE THREAD

**Issue by nznmol** [cytomine/Cytomine-bootstrap#10]
So I manged to get a seemingly working local deployment of cytomine - yeahy :)

Created a project, uploaded pictures, added some annotations... then I wanted to do something jobs related, but under the Configuration tab for my project, under Softwares, the drop down menu was empty :(

Looking at the docs, I saw somewhere that `software_router` is responsible for providing the software. Inspecting my local algo store (`/data/algo`) there were a bunch of folders, so that seemed in order.

Looking at the logs of `software_router`, there were a bunch of errors / messages that I at first glance didn't understand. After studying them a bit more intensely, looking at the dockerfile, the deploy script and the wrapdocker file, I still didn't understand much, but came to realize that your running docker in docker! Nice. But why not use the offical dind image? Or, alternatively, just mount the docker socket? You're running with privileged anyways. For your own sake, I would highly recommend refactoring that - I can be of service, if you point me in the right direction.

Finally, I did what had to be done - restarted the container :D Now I got all of four softwares to choose from, `CellCounter_{CNN,ET}_{Predictor,Model_Builder}`. Cool! Figured I'd restart again, see if that gives me more algos to choose from. Unfortunately, it didn't...

If I can make another remark: On my first inspection of the container, the container state was running, but when I ran `ps aux` in the container, there was nothing but emptyness and a sad `tail` to look upon. The container should die when the main applications inside are not running, otherwise it's hard to notice failure. Again, if you point me in the right direction (cf. #8), I'd be happy to supply a merge request.

Is there anything I should do to my system to make the whole docker in docker thing run smoothly? I would guess that this should only come up once I try to submit a job...

Or are the python script that are supposed to add the software somehow malfunctioning?

Would really appreciate some help with this one!

Please check out a [gist to the logs from `software_router`](https://gist.github.com/nznmol/07d0d4abc4cae9e14b79ec95c397eaf8) if you feel like reading some logs.

**Comment by nznmol** [comment]
Additional info, not sure if related: imagefilters dropdown is empty as well.

**Comment by geektortoise** [comment]
Hello, 

Docker in Docker is a feature not used in production but it was a test that lead to a new way of adding external scripts.
To allow a easiest way to add new scripts in production, the ULiège team (with @urubens ) is currently working on a new architecture based on Docker and Singularity.
http://doc.cytomine.be/display/ALGODOC/%5BHOWTO%5D+Manage+software+and+servers+for+administrators#id

These features (on the Cytomine-ULiège repositories) are not yet available in production.

**Comment by nznmol** [comment]
okay, cool, thanks for that info! I read the docs about managing software repos.

I see that you plan to integrate it in the web api - in the meanwhile, I also see those four lines of python for adding a repo manually : )

Tried to run them, had to find the right repo for the cytomine python client (cf. [an issue about its availability on pypi](https://github.com/cytomine/Cytomine-python-client/issues/14)), managed, and ran the script (and got a 200 response). I used the core url as host, the superadmin pub and priv keys, and the cytomine uliege repository as written in the docs.

And then - nothing yet. Ok, gotta restart the software-router container, did that, still nothing. hm. let's look at the docs again. aha, gotta go to 
```
http://_YOUR_CYTOMINE_CORE_URL/api/software_user_repository/refresh_user_repositories.json
```

to force a refresh of the repos. But here I'm getting a 404 : (

I'm running from this repository, the ULiegeDev branch. Is that the problem? Should I use a branch from the [Cytomine-ULiege/Cytomine-bootstrap project](https://github.com/Cytomine-ULiege/Cytomine-bootstrap)? If so, which one?

software router logs look as follows:

```
mv: cannot stat �/tmp/config.groovy�: No such file or directory
tail: unrecognized file system type 0x794c7630 for �/tmp/log.out�. please report this to bug-coreutils@gnu.org. reverting to polling
Exception in thread "main" java.lang.NullPointerException
        at be.cytomine.client.collections.Collection.size(Collection.java:66)
        at be.cytomine.client.collections.Collection$size.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at be.cytomine.software.consumer.Main.launchRepositoryManagerThread(Main.groovy:99)
        at be.cytomine.software.consumer.Main.main(Main.groovy:74)
2018-07-29 12:02:32 INFO  Main:47 - GROOVY_HOME : null
2018-07-29 12:02:32 INFO  Main:47 - PATH : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2018-07-29 12:02:32 INFO  Main:47 - Launch repository thread
2018-07-29 12:02:32 INFO  Cytomine:282 - fetchCollection=/api/software_user_repository.json?&max=0&offset=0
2018-07-29 12:02:32 INFO  HttpClient:123 - Connection to http://localhost-core/api/software_user_repository.json?&max=0&offset=0
2018-07-29 12:02:32 INFO  Cytomine:293 - 404
```

**Comment by geektortoise** [comment]
Hello
1) It is strange that the config.groovy file is not found, 
As you are running the ULiège branch, can you refetch their docker image ?
sudo docker pull cytomineuliege/software_router

2) The localhost-core is reachable from the software_router container ?
sudo docker exec -it software_router bin/bash
curl localhost-core
