### ISSUE TITLE
Enable 3rd party access

### ISSUE THREAD

**Issue by AustinGil** [cytomine/Cytomine-bootstrap#18]
My company is testing out Cytomine, and it looks really great. I've been asked to build a custom UI that integrates with the Cytomine API, but I just keep getting CORS issues any time I try to make a fetch request to the API.

The request looks like:
```js
fetch(`${HOST}/api/ontology.json`, {
  credentials: "include",
  headers: {
    "proxy-authorization":
      "Basic [some code]",
    "proxy-connection": "keep-alive",
  },
  mode: "cors",
})
```

But I keep getting the error:
```
Access to fetch at '[MY HOST]/api/ontology.json' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

Is there any way to open up access to the API for 3rd party requests?

**Comment by geektortoise** [comment]
[My answer](https://github.com/cytomine/Cytomine-core/issues/1184#issuecomment-611399499)

**Comment by geektortoise** [comment]
For the record, the nginx CORS configuration worked for Chrome and Firefox but still happened in Brave browser.
