### ISSUE TITLE
postgis docker image build failing

### ISSUE THREAD

**Issue by jacmarjorie** [cytomine/Cytomine-bootstrap#2]
I'm having issues building the postgis image due to a 404 with postgresql-9.3-postgis deb. This was working about two weeks ago, but now these can't be fetched. 

[Source line](https://github.com/cytomine/Cytomine-bootstrap/blob/master/postgis/Dockerfile#L24)

```
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgis/liblwgeom-2.2-5_2.2.1+dfsg-2.pgdg14.04+1_amd64.deb  404  Not Found [IP: 87.238.57.227 80]

E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgis/postgresql-9.3-postgis-scripts_2.2.1+dfsg-2.pgdg14.04+1_all.deb  404  Not Found [IP: 87.238.57.227 80]

E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgis/postgresql-9.3-postgis-2.2_2.2.1+dfsg-2.pgdg14.04+1_amd64.deb  404  Not Found [IP: 87.238.57.227 80]

```

**Comment by geektortoise** [comment]
Hello, 
I don't have this problem with the last postgis Dockerfile on the repo.
Can you retest with

`cd postgis/ && 
sudo docker build --no-cache -t="cytomine/postgis" .` 
?

Maybe the previous apt-get update -y was not plainfully launched.

You can delete the image `sudo docker rmi cytomine/postgis` and rebuild it.
Or add an apt-get update -y before the installation of the package with this problem.

**Comment by jacmarjorie** [comment]
I believe this was an issue specific to my environment. It has since been resolved. Thank you!
