### ISSUE TITLE
Is NGINX networking configuration correct? 

### ISSUE THREAD

**Issue by AustinGil** [cytomine/Cytomine-bootstrap#24]
Doing a bit of customization to use my own frontend and running into issues with the NGINX config. When testing with `/usr/local/nginx/sbin/nginx -t`, I got:
```
nginx: [emerg] host not found in upstream "web_ui" in /usr/local/nginx/conf/nginx.conf:96
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
```

I'm no NGINXpert (:D) but it seems like there may be a networking error, and Im wondering if it's related to the Docker container being called `web_UI` (uppercase) but the NGINX conf referencing `web_ui` (lowercase)

See these lines:
 
https://github.com/cytomine/Cytomine-bootstrap/blob/20b48f6c8a8feae9c9159162b6a7b98fcb5defa6/start_deploy.sh.sample#L131

https://github.com/cytomine/Cytomine-bootstrap/blob/20b48f6c8a8feae9c9159162b6a7b98fcb5defa6/configs/nginx/nginx.conf.sample#L54

I had to comment out the following line for it to work:
```
location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_pass http://web_ui;
}
```

And also note that I actually tested with `proxy_pass http://web_UI;` and it also did not work, so it's possible I'm totally off base here.

**Comment by geektortoise** [comment]
Hello, 

As we are working with Docker, we always need to know at which level we are working.
When I am testing from the nginx container, it works fine
```
$ sudo docker exec -it nginx bash
# /usr/local/nginx/sbin/nginx -t
nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/nginx/conf/nginx.conf test is successful
```
Because the web_ui is set in the /etc/hosts file of the container

```
# cat /etc/hosts
....
172.17.0.2	web_UI 0d17d6ae4247
```

http://web_ui or http://web_UI are, as URL, case insensitive and returns the same html page.

```
<!DOCTYPE html><html>...<noscript><strong>We're sorry but this Cytomine Web-UI doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript>...</html>
```

If you are working from outside the nginx container, you need to reference the web_UI container IP or configure the nginx to redirect a specific url to this container as your machine doesn't know the "web_UI" domain name.

Have a nive day.

**Comment by AustinGil** [comment]
Ah ok. I thought this was set up to use Docker's networking so that you actually can reference a different docker container by name (such as "web_ui"). I thought that was what was happening here.

**Comment by AustinGil** [comment]
Did some more testing on my end, and in fact, the "web_ui" DOES reference the Docker network link as I had thought. But the issue was on my end. I had a custom script to just restart the nginx docker container, but I had left out the `--link` part for the web_UI. So therefore, Docker never made the connection.

Thanks for the response. It was helpful in debugging.
