### ISSUE TITLE
Auto-restart when host starting up not working (cannot enable tty mode on non tty input)

### ISSUE THREAD

**Issue by soltiger** [cytomine/Cytomine-bootstrap#3]
I have set up Cytomine to start when host is staring up following these instructions:
[Auto-restart when host starting up](http://confluence.cytomine.be/display/PubOp/Auto-restart+when+host+starting+up)

However, when I run command `systemctl status cytomine.service`, following error keeps repeating multiple times and the Cytomine won't start:

> Apr 27 14:49:26 xxxx sudo[5787]:     root : TTY=unknown ; PWD=/home/yyyy/Cytomine-bootstrap-original ; USER=root ; COMMAND=/bin/docker exec -i -t core tail -n 200 /var/lib/tomcat7/logs/catalina.out
> Apr 27 14:49:26 xxxx restart_keep_data.sh[2208]: cannot enable tty mode on non tty input

I'm running CentOS Linux release 7.2.1511.

**Comment by geektortoise** [comment]
With the --restart=unless-stopped argument, the containers restart natively.
I close this issue.
