### ISSUE TITLE
Bad login or password in Cytomine Ubuntu 18.04

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/Cytomine-bootstrap#31]
Hi, I just installed Cytomine in my Ubuntu 18.04 machine, but I did the 'init.sh' and 'start.sh' twice because I mistakenly create data paths directories inside /home.  

I've tried `sudo sh clean_docker_keep_data.sh`

And it returned `sh: 0: Can't open clean_docker_keep_data.sh`

For `sudo docker volume rm postgis_data #clean the database`

It returned `Error: No such volume: postgis_data`

I'm stuck at this for hours. I've tried 'clean_config.sh', delete all the containers in docker and rerun the 'init.sh' and 'start.sh' but it still returned 'Bad login or password'.

I really appreciate your kind assistance. Thank you.

_Originally posted by @mizjaggy18 in https://github.com/cytomine/Cytomine-bootstrap/issues/17#issuecomment-754765126_

**Comment by mizjaggy18** [comment]
Weehoo! Just found the solution, as below (in sudo mode):

bash stop.sh
docker volume prun
bash clean_config.sh 
bash init.sh 
bash start.sh

**Comment by geektortoise** [comment]
Note that clean_config.sh doesn't exist in this repository.

I guess you were using this version : https://github.com/Cytomine-ULiege/Cytomine-bootstrap/

**Comment by mizjaggy18** [comment]
> Note that clean_config.sh doesn't exist in this repository.
> 
> I guess you were using this version : https://github.com/Cytomine-ULiege/Cytomine-bootstrap/

Yes I use ULiege version. Oh my bad I didn't realize it was different. Thank you so much for pointing out.
