### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by AustinGil** [cytomine/Cytomine-bootstrap#33]
I was wondering if there is a way to delete users? I dont see any option in the UI, and I even tried updating the `deleted` column in the `sec_user` table, but users could still log in. For now I'm just "locking" the user.

**Comment by geektortoise** [comment]
Hello, 

There is no current way to delete the users. If you don't want them to connect, you are able to lock them.

We need to solve all the dependencies linked to an user for a deletion.

**Comment by geektortoise** [comment]
I will use the ticket #1199 for evolution of this features.

**Comment by AustinGil** [comment]
OK. I understand your decision and just wanted to add that this may be a desired feature for GDPR compliance. Users have the "right to be forgotten" which means any organization must respect a request to delete user data.
