### ISSUE TITLE
Change working paths

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/Cytomine-bootstrap#34]
Hi @geektortoise,

I have an issue with changing the working paths. I'm using Ubuntu Server 18.04. I want to change them as below: 

#Paths
IMS_STORAGE_PATH=/home/admincyto/data/images
IMS_BUFFER_PATH=/home/admincyto/data/images/_buffer
BACKUP_PATH=/home/admincyto/data/backup
ALGO_PATH=/home/admincyto/data/algo

After saving the changes inside `configuration.sh`, I run `bash init.sh` and `sudo sh restart.sh`.

But I cannot upload any image, there is an 'Upload error'. Looks like the images are stuck in '/home/admincyto/data/images/_buffer' folder. Is there anywhere else I need to modify to change the working path?  
![image](https://user-images.githubusercontent.com/77017051/111571411-a3f11380-879e-11eb-9bd0-0862007d4c85.png)

![image](https://user-images.githubusercontent.com/77017051/111571810-490bec00-879f-11eb-8be1-873370e47e89.png)
![image](https://user-images.githubusercontent.com/77017051/111571835-55904480-879f-11eb-972b-3d61bed5f2e6.png)
![image](https://user-images.githubusercontent.com/77017051/111571887-7062b900-879f-11eb-8fd2-e0250be5b86d.png)
![image](https://user-images.githubusercontent.com/77017051/111571953-96885900-879f-11eb-9a20-864e26bf3055.png)

**Comment by geektortoise** [comment]
Maybe a permission issue ?

As the upload is manage by the IMS component, you can inspect the logs with
`sudo docker logs ims`

To be sure that I understand correctly, it is an existing installation where you try to modify the paths.
Did you moved the old directory at the new locations ?

(The IMS_STORAGE_PATH is mapped between server and container at the same locations)

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

`sudo docker logs ims` returns very lengthy output. I attached the part of the log file, because the 'quartzScheduler_Worker' is repeated hundreds or even thousands time. 
[logs-ims-19032021.log](https://github.com/cytomine/Cytomine-bootstrap/files/6168535/logs-ims-19032021.log)

>  To be sure that I understand correctly, it is an existing installation where you try to modify the paths.
Did you moved the old directory at the new locations ?

Yes it is an existing installation, and I didn't move the old directory. 
1. Can I just cut-paste the /data from the root into the /home/admincyto directory?
2. Since I already run `bash init.sh` and `sudo sh restart.sh`, would not it be sufficient to remap the server & container?

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

I just moved the old directory to the new locations, and here is the output of `sudo docker logs ims`. 
[logs-ims-23032021.log](https://github.com/cytomine/Cytomine-bootstrap/files/6188407/logs-ims-23032021.log)
Looks like a permission issue, but there is a `chmod -R 777` already. Anything we can do to fix this? Please advise.

**Comment by mizjaggy18** [comment]
Hi,

I've tried several ways to enable permission, even manually set `chmod -R 777` to  the `/data` folder but none of them work. The last resort is to do the following:

1. Uninstall Cytomine using [this guide](https://documentation.cytomine.org/How-to-uninstall-Cytomine?structure=Admins) 
2. Keep `Cytomine_bootstrap` folder as it is
3. Set the desired `data path` in `configuration.sh`. To use /data in /home partition, just use `~/data`
4. Run `bash init.sh` and `sudo sh restart.sh` 
 
Now everything is working perfectly! Thank you so much @geektortoise for your initial guidance.
