### ISSUE TITLE
Fail to load image due to CORS (Cross-Origin Request Blocked) for https site 

### ISSUE THREAD

**Issue by vewe-richard** [cytomine/Cytomine-bootstrap#47]
**Describe the bug**
Yes, Followed official documentation to install Cytomine on local ubuntu laptop.
I cloned this repo and checked out 'ssl' branch as I planned to host Cytomine on a https site. 
I changed nothing except prepared necessary certificate file and key.
Everything went well, except when uploaded a image.
It failed and Firefox reported,
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost-upload/upload?cytomine=https://localhost-core&idStorage=90&idProject=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

Screen cut of the problem
[https://github.com/vewe-richard/issue-report/blob/main/image_2022_09_23T11_25_10_118Z.png](url)

**Copy your configuration file**
I used the origin configuration file
CORE_URL=localhost-core
IMS_URL1=localhost-ims
IMS_URL2=localhost-ims2
UPLOAD_URL=localhost-upload

**Web context:**
As Cytomine is a web platform, give us any information that will help us to identify the problem.
- Is it installed on a remote server or on your local machine ?
On local machine

- Which operating system and distribution is running ?
Ubuntu 20.04

**Comment by vewe-richard** [comment]
Almost the same in Chrome,  it seems like an https URL nested in another https URL, which cause policy issue.
`POST https://localhost-upload/upload?cytomine=https://localhost-core&idStorage=90&idProject= net::ERR_CERT_AUTHORITY_INVALID  

(anonymous)	@	xhr.js:177  
t.exports	@	xhr.js:13
t.exports	@	dispatchRequest.js:52
Promise.then (async)		
u.request	@	Axios.js:61
r.forEach.u.<computed>	@	Axios.js:87
(anonymous)	@	bind.js:9
startUpload	@	CytomineStorage.vue:419
click	@	CytomineStorage.vue?42f2:3
ne	@	vue.runtime.esm.js:1854
n	@	vue.runtime.esm.js:2179
Ji.o._wrapper	@	vue.runtime.esm.js:6917`

Screen cut of the problem
[https://raw.githubusercontent.com/vewe-richard/issue-report/main/image_2022_09_23T11_23_26_350Z.png](url)

**Comment by gvincke** [comment]
If you host Cytomine on your local machine, there is absolutely no need to be in HTTPS. Stay in HTTP and follow the main documentation to host your Cytomine on your local machine. HTTPS in needed when a web service is open to the internet.

**Comment by gvincke** [comment]
This being said, have you done this step ?
![image](https://user-images.githubusercontent.com/1370541/191955104-476adcb2-193c-437b-8664-a5f4ca31139e.png)
So in your case you should have in your /etc/hosts these values :
```
127.0.0.1 localhost-core
127.0.0.1 localhost-ims
127.0.0.1 localhost-ims2
127.0.0.1 localhost-upload
127.0.0.1 rabbitmq
```

**Comment by vewe-richard** [comment]
Yes, I want to host Cytomine on the internet, I got CORS issue, and had no idea.
So, I came to local machine to check if still problem.
Yes, I configured /etc/hosts. 
Everything is ok, includes create project, but when I tried to upload pictures, it failed.
It doesn't have such problem when I host Cytomine in http.

**Comment by vewe-richard** [comment]
This is the site I setup, everything is OK except uploading image & pictures. 

[https://ap-demo-core.labflow.ai/#/](url)

user: admin
password: d7bc1ca4-faaa-4913-b16a-acd1a89210e4

**Comment by vewe-richard** [comment]
`Access to XMLHttpRequest at 'https://ap-demo-upload.labflow.ai/upload?cytomine=https://ap-demo-core.labflow.ai&idStorage=90&idProject=276' from origin 'https://ap-demo-core.labflow.ai' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by vewe-richard** [comment]
Fixed.
It's due to the cros https prefilight request are sent to 80 port, not 443 port.

configs/nginx/nginx.conf.sample, add listen 80 to upload section.
`server {                                                                                                                                                                                                
        listen 80;                                                                                                                                                                                          
        client_max_body_size 0;                                                                                                                                                                             
        listen       443 ssl;                                                                                                                                                                               
        server_name  $UPLOAD_URL;                                                                                                                                                                           
                                                                                                                                                                                                            
        ssl_certificate /etc/letsencrypt/live/$UPLOAD_URL/fullchain.pem;                                                                                                                                    
        ssl_certificate_key /etc/letsencrypt/live/$UPLOAD_URL/privkey.pem;                                                                                                                                  
        include ssl.conf;                                                                                                                                                                                   
                                                                                                                                                                                                            
        # Upload form should be submitted to this location                                                                                                                                                  
        location /upload {                                                                                                                                                                                  
            proxy_read_timeout 600;            `
