### ISSUE TITLE
Failed to delete the uploaded file(unexpected error)

### ISSUE THREAD

**Issue by vewe-richard** [cytomine/Cytomine-bootstrap#48]
Can not delete image
- Have you followed [our documentation](https://documentation.cytomine.org/) ?  Yes
- Description : 
   1. upload image
   2. add image to a project
   3. delete image from project
   4. delete image for #storage page, it reports "Failed to delete the uploaded file(unexpected error)"

**Copy your configuration file**
ubuntu@ip-10-0-1-50:~/cytomine-bootstrap$ git diff configuration.sh
diff --git a/configuration.sh b/configuration.sh
index c3047ec..44345b4 100644
--- a/configuration.sh
+++ b/configuration.sh
@@ -15,11 +15,10 @@
 #
 
 #URLs
-CORE_URL=localhost-core
-IMS_URL1=localhost-ims
-IMS_URL2=localhost-ims2
-UPLOAD_URL=localhost-upload
-
+CORE_URL=ap-staging-core.labflow.ai
+IMS_URL1=ap-staging-ims.labflow.ai
+IMS_URL2=ap-staging-ims2.labflow.ai
+UPLOAD_URL=ap-staging-upload.labflow.ai

**Web context:**
As Cytomine is a web platform, give us any information that will help us to identify the problem.
- Is it installed on a remote server or on your local machine ?
  On a remote server
- Which operating system and distribution is running ?
  On ubuntu 22.04
  master branch latest
  ----------------------------------------------------------------------------------------------------
ubuntu@ip-10-0-1-50:~/cytomine-bootstrap$ git branch
* master                              
  tomaster
ubuntu@ip-10-0-1-50:~/cytomine-bootstrap$ git log                                                     
commit e2eec9162b163087d6dcdafbeb3fe4985289b446 (HEAD -> master, origin/master, origin/HEAD)
Author: TheGeekTortoise <Renaud.Hoyoux@yahoo.fr>
Date:   Thu Sep 1 12:16:07 2022 +0200

    update slurm version

   ------------------------------------------------------------------------------------------------------

**Comment by vewe-richard** [comment]
![image](https://user-images.githubusercontent.com/13496173/198758083-607ebec8-3bb1-4811-a677-ef0095cd50b6.png)

**Comment by vewe-richard** [comment]
sudo docker logs -f core
29-10-2022 00:59:22,631 WARN ConstraintException - This slice be.cytomine.image.AbstractSlice : 2418 cannot be deleted as it has already been insert in projects [test2]
29-10-2022 00:59:22,631 ERROR RestController - This slice be.cytomine.image.AbstractSlice : 2418 cannot be deleted as it has already been insert in projects [test2]


But I had deleted this image from test2 project.

**Comment by vewe-richard** [comment]
Should I write this issue to https://github.com/cytomine/Cytomine-core?

**Comment by vewe-richard** [comment]
fixed

**Comment by scandel** [comment]
Hello, I'm facing the same problem, could you please explain how you solved it?
