### ISSUE TITLE
Installation of test data and uploading of images fails

### ISSUE THREAD

**Issue by choosehappy** [cytomine/Cytomine-bootstrap#5]
I am following the directions as posted here:

http://confluence.cytomine.be/pages/viewpage.action;jsessionid=E5AFD7CC6870DD32CD940977F220991D?pageId=10715266

I have done step 1 and 2 without problem
Step 3 didn’t seem to require any changes as I wanted a local server to test out
For step 3.1, I added all the requested hosts to the host file

I then did step 4, when it asked if I wanted to install test data, I said yes
The results was:
_Data test in installation.
Data are not plainfully injected. Please check the status with the command docker logs data_test.
End of the installation._

There was no sample data installed, additionally, after manually making a new project and attempting to upload an image, the result simply said “Error: True”

![image](https://user-images.githubusercontent.com/9681868/30356568-acd78bc6-9807-11e7-80a9-57f4e549c952.png)

**Comment by geektortoise** [comment]
Hello !
The data are add with the jsnow account. So to see them, active the admin mode (top right drop-down-list).

Does the application have wirting rights on the IMS_STORAGE_PATH ?
If upload are'nt working, check the error message with sudo docker logs ims

**Comment by rmaree** [comment]
Same problem with v1.1. data are not plainfully injected.
In my case it always fails for the same image (after correctly injecting others):

Status: Downloaded newer image for cytomine/data_test:v1.1
Data test in installation.
Data are not plainfully injected. Please check the status with the command docker logs data_test.
End of the installation.

> sudo docker logs data_test:

add project DEMO-EMPTY
2017-09-21 17:41:27 INFO  HttpClient:132 - Connection to http://localhost-core/api/project.json
2017-09-21 17:41:27 INFO  HttpClient:132 - Connection to http://localhost-core/api/user/clannister.json
2017-09-21 17:41:27 INFO  HttpClient:132 - Connection to http://localhost-core/api/project/4967/user/37.json
2017-09-21 17:41:27 INFO  HttpClient:132 - Connection to http://localhost-core/api/user/estark.json
2017-09-21 17:41:27 INFO  HttpClient:132 - Connection to http://localhost-core/api/project/4967/user/35.json
2017-09-21 17:41:27 INFO  Cytomine:267 - fetchCollection=/api/software.json?&max=0&offset=0
2017-09-21 17:41:27 INFO  HttpClient:132 - Connection to http://localhost-core/api/software.json?&max=0&offset=0
2017-09-21 17:41:27 INFO  Cytomine:278 - 200
DATA INJECTED. SOME ERRORS OCCURED :
The image /tmp/script/./DEMO-CLASSIFICATION-CELL/images/cells4.png was not uploaded
An annotation cannot be added on image instance /tmp/script/./DEMO-CLASSIFICATION-CELL/images/cells4.png
END OF DATA INJECTION

**Comment by aled88** [comment]
hi i am also still having this issue even after trying install and reinstall 
sudo sh clean_docker.sh
sudo docker rmi $(sudo docker images -q)
sudo sh ./start_deploy.sh

`injectedAnnotation.terms=[######### Term Negative]
[parent:null, deleted:null, color:#ff0000, rate:null, created:1510391573301, name:Negative, comment:null, id:4414, class:be.cytomine.ontology.Term, updated:null, ontology:4406]
2017-11-11 09:20:12 INFO  HttpClient:132 - Connection to http://localhost-core/api/annotation/5005/term/4414.json?annotationIdent=5005
2017-11-11 09:20:12 INFO  HttpClient:132 - Connection to http://localhost-core/api/annotation.json
injectedAnnotation.terms=[######### Term Negative]
[parent:null, deleted:null, color:#ff0000, rate:null, created:1510391573301, name:Negative, comment:null, id:4414, class:be.cytomine.ontology.Term, updated:null, ontology:4406]
2017-11-11 09:20:12 INFO  HttpClient:132 - Connection to http://localhost-core/api/annotation/5018/term/4414.json?annotationIdent=5018
2017-11-11 09:20:12 INFO  HttpClient:132 - Connection to http://localhost-core/api/annotation.json
2017-11-11 09:20:12 INFO  HttpClient:132 - Connection to http://localhost-core/api/annotation.json
injectedAnnotation.terms=[######### Term Positive]
[parent:null, deleted:null, color:#00ff00, rate:null, created:1510391573377, name:Positive, comment:null, id:4426, class:be.cytomine.ontology.Term, updated:null, ontology:4406]
2017-11-11 09:20:12 INFO  HttpClient:132 - Connection to http://localhost-core/api/annotation/5031/term/4426.json?annotationIdent=5031
DATA INJECTED. SOME ERRORS OCCURED :
The image /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG2.jp2 was not uploaded
The image /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2 was not uploaded
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
An annotation cannot be added on image instance /tmp/script/./DEMO-SEGMENTATION-TISSUE/images/LUNG1.jp2
The image /tmp/script/./DEMO-CLASSIFICATION-CELL/images/cells4.png was not uploaded
An annotation cannot be added on image instance /tmp/script/./DEMO-CLASSIFICATION-CELL/images/cells4.png
An annotation cannot be added on image instance /tmp/script/./DEMO-CLASSIFICATION-CELL/images/cells2.png
END OF DATA INJECTION
`

**Comment by bpavie** [comment]
I have exactly the same error as choosehappy.
I also tried to install the demo dataset and it failed as described by rmaree.
The demo dataset appears then in Pink tiles as mention in http://confluence.cytomine.be/display/PubOp/Known+problems+of+v1.0

Any progress on this issue?
