### ISSUE TITLE
web docs missing a step

### ISSUE THREAD

**Issue by nznmol** [cytomine/Cytomine-bootstrap#7]
trying to follow the [docs for installing with docker](http://doc.cytomine.be/pages/viewpage.action?pageId=10715266#id-[HOWTO]AutomaticInstallationwithDocker(Ubuntu14.04LTS+)-Step1-RetrieveCytomine-bootstrap), I now noticed that the step of running `init.sh` is mysteriously missing, which led me to believe that the `.sample` files have to be renamed, a line for reading variables from `configuration.sh` added, etc.

couldn't find the source for the docs, otherwise I would have gladly supplied a merge request - sorry if this is not quite the right place for this issue.

**Comment by geektortoise** [comment]
Hello, 

This is the right place.

I'm currently writing the documentation for the installation, sorry for the inconvenience.
The link you have is to install the ULiège branch.

Have a nice day

**Comment by geektortoise** [comment]
Documentation is now at [this link](https://documentation.cytomine.org/Admins)
