### ISSUE TITLE
Confusion about branches and docker images

### ISSUE THREAD

**Issue by nznmol** [cytomine/Cytomine-bootstrap#8]
Trying to deploy cytomine locally on one host using docker, i've been unsuccessful. have tried all three branches (dev master dev-uliege).

Could you please explain your branching strategy - what is the most recent branch? Which one are you maintaining?

I also noticed that different tags are used for the docker images in the different branches - and that there are docker files available in different repositories and branches. But I can't tell which dockerfile is associated with which tag D : that makes debugging super hard... if you could provide the dockerfiles for the respective tags on the docker hub, that would be a great help.

I suspect that there's not much development going on here anymore, at least not on all branches, but it would be great if latest efforts could be consolidated in one working branch. I'm ready to help and submit pull requests, but I honestly don't even know where to start, i.e. which branch to pick as a starting point.

I appreciate that you're making the deployment available through docker, and there's obviously many moving parts, and it's a complex system, so I'd be happy to help out there.

**Comment by geektortoise** [comment]
Branching strategy : 

- Master
- ULiege : This branch is supposed to be a mirror of the master branch of the official repository of the University of Liège (https://github.com/Cytomine-ULiege/Cytomine-bootstrap/)
- others : development branches

The previous dev branch have been merged recently and is now deleted.
The Dockerfiles have been moved to another repository (https://github.com/cytomine/Dockerfiles) as it is not necessary to rebuild the docker image when you change the usual configuration.

I don't have github tags on the Dockerfiles repo associated with Dockerhub tags but it is of course a good idea. We will do that for the next tags.

**Comment by nznmol** [comment]
Thanks a bunch for the response, that makes it clear : )
