### ISSUE TITLE
commenting out iipoff leads to invalid nginx config

### ISSUE THREAD

**Issue by nznmol** [cytomine/Cytomine-bootstrap#9]
in the uliege dev branch, [iipoff is commented out in the deployment script (in many places, but in particular for nginx)](https://github.com/cytomine/Cytomine-bootstrap/blob/293900a984a6caf1d643a74fa10380222a1ffa2e/start_deploy.sh#L236) - but the sample config of nginx has a config entry for iipoff.

since the variable `IIP_OFF_URL` is not set, the respecitve string in the nginx config ends up being empty after the nginx deploy script did its magic, and the config becomes invalid.

**Comment by geektortoise** [comment]
Hello, 
This branch is supposed to be a mirror of the master branch of the official repository of the University of Liège (https://github.com/Cytomine-ULiege/Cytomine-bootstrap/)

The branch is up to date with the official repo now.

**Comment by nznmol** [comment]
fixed now, on ULiegeDev at 1bab814.
